x = {
    'created_at': 'Wed Sep 20 22:32:38 +0000 2017',
    'id': 910632822993412096,
    'id_str': '910632822993412096',
    'text': '@RevisaMiGrieta Varios edificios en Paseos de Taxqueña Prolongación Río Churubusco 345, xfavor vengan… https://t.co/VBwdijaTiR',
    'truncated': True,
    'entities': {
        'hashtags': [],
        'symbols': [],
        'user_mentions': [{
            'screen_name': 'RevisaMiGrieta',
            'name': 'Revisa Mi Grieta',
            'id': 910368552095551489,
            'id_str': '910368552095551489',
            'indices': [0, 15]
        }],
        'urls': [{
            'url': 'https://t.co/VBwdijaTiR',
            'expanded_url': 'https://twitter.com/i/web/status/910632822993412096',
            'display_url': 'twitter.com/i/web/status/9…',
            'indices': [103, 126]
        }]
    },
    'metadata': {
        'iso_language_code': 'es',
        'result_type': 'recent'
    },
    'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    'in_reply_to_status_id': None,
    'in_reply_to_status_id_str': None,
    'in_reply_to_user_id': 910368552095551489,
    'in_reply_to_user_id_str': '910368552095551489',
    'in_reply_to_screen_name': 'RevisaMiGrieta',
    'user': {
        'id': 65275867,
        'id_str': '65275867',
        'name': 'Fan',
        'screen_name': 'FanMor',
        'location': '',
        'description': 'Sagitario, Puma, Enojona y fan de las malteadas con piquete.',
        'url': None,
        'entities': {
            'description': {'urls': []}
        },
        'protected': False,
        'followers_count': 528,
        'friends_count': 1119,
        'listed_count': 8,
        'created_at': 'Thu Aug 13 04:36:36 +0000 2009',
        'favourites_count': 648,
        'utc_offset': -18000,
        'time_zone': 'Mexico City',
        'geo_enabled': True,
        'verified': False,
        'statuses_count': 18873,
        'lang': 'es',
        'contributors_enabled': False,
        'is_translator': False,
        'is_translation_enabled': True,
        'profile_background_color': 'F5ABB5',
        'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/603601846557540352/-4bgecam.jpg',
        'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/603601846557540352/-4bgecam.jpg',
        'profile_background_tile': True,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/860159383753437184/POxu6EKf_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/860159383753437184/POxu6EKf_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/65275867/1488348153',
        'profile_link_color': 'F5ABB5',
        'profile_sidebar_border_color': 'EEEEEE',
        'profile_sidebar_fill_color': 'F6F6F6',
        'profile_text_color': '333333',
        'profile_use_background_image': True,
        'has_extended_profile': True,
        'default_profile': False,
        'default_profile_image': False,
        'following': False,
        'follow_request_sent': False,
        'notifications': False,
        'translator_type': 'none'
    },
    'geo': None,
    'coordinates': None,
    'place': None,
    'contributors': None,
    'is_quote_status': False,
    'retweet_count': 0,
    'favorite_count': 0,
    'favorited': False,
    'retweeted': False,
    'possibly_sensitive': False,
    'lang': 'es'
}